#Set Working Directory to folder with test data
setwd("C:/Users/slussetc/Desktop/UCI HAR Dataset/test")
#Read in test data
x_test<-read.table("x_test.txt")
y_test<-read.table("y_test.txt")
colnames(y_test)<-c("ActNumber")
#Set Working Directory to folder with training data
setwd("C:/Users/slussetc/Desktop/UCI HAR Dataset/train")
#Read in training data
x_train<-read.table("x_train.txt")
y_train<-read.table("y_train.txt")
colnames(y_train)<-c("ActNumber")
#Set Working Directory to folder with attribute labels
setwd("C:/Users/slussetc/Desktop/UCI HAR Dataset")
#Read in attribute names
features<-read.table("features.txt")
#Read in activity labels
activity_labels<-read.table("activity_labels.txt")
colnames(activity_labels)<-c("ActNumber","ActName")
#Merge on Activity Labels
y_test<-merge(y_test,activity_labels,by="ActNumber")
y_train<-merge(y_train,activity_labels,by="ActNumber")
#Create Tidy Data with Column for Activity, Feature, Mean, Standard Deviation for test
test<-data.frame(Activity=y_test[,2],Feature=rep("tBodyAcc X",2947),Mean=x_test[,1],StdDev=x_test[,4])
test<-rbind(test,data.frame(Activity=y_test[,2],Feature=rep("tBodyAcc Y",2947),Mean=x_test[,2],StdDev=x_test[,5]))
test<-rbind(test,data.frame(Activity=y_test[,2],Feature=rep("tBodyAcc Y",2947),Mean=x_test[,3],StdDev=x_test[,6]))
test<-rbind(test,data.frame(Activity=y_test[,2],Feature=rep("tGravityAcc X",2947),Mean=x_test[,41],StdDev=x_test[,44]))
test<-rbind(test,data.frame(Activity=y_test[,2],Feature=rep("tGravityAcc Y",2947),Mean=x_test[,42],StdDev=x_test[,45]))
test<-rbind(test,data.frame(Activity=y_test[,2],Feature=rep("tGravityAcc Z",2947),Mean=x_test[,43],StdDev=x_test[,46]))
test<-rbind(test,data.frame(Activity=y_test[,2],Feature=rep("tBodyAccJerk X",2947),Mean=x_test[,81],StdDev=x_test[,84]))
test<-rbind(test,data.frame(Activity=y_test[,2],Feature=rep("tBodyAccJerk Y",2947),Mean=x_test[,82],StdDev=x_test[,85]))
test<-rbind(test,data.frame(Activity=y_test[,2],Feature=rep("tBodyAccJerk Z",2947),Mean=x_test[,83],StdDev=x_test[,86]))
test<-rbind(test,data.frame(Activity=y_test[,2],Feature=rep("tBodyGyro X",2947),Mean=x_test[,121],StdDev=x_test[,124]))
test<-rbind(test,data.frame(Activity=y_test[,2],Feature=rep("tBodyGyro Y",2947),Mean=x_test[,122],StdDev=x_test[,125]))
test<-rbind(test,data.frame(Activity=y_test[,2],Feature=rep("tBodyGyro Z",2947),Mean=x_test[,123],StdDev=x_test[,126]))
test<-rbind(test,data.frame(Activity=y_test[,2],Feature=rep("tBodyGyroJerk X",2947),Mean=x_test[,161],StdDev=x_test[,164]))
test<-rbind(test,data.frame(Activity=y_test[,2],Feature=rep("tBodyGyroJerk Y",2947),Mean=x_test[,162],StdDev=x_test[,165]))
test<-rbind(test,data.frame(Activity=y_test[,2],Feature=rep("tBodyGyroJerk Z",2947),Mean=x_test[,163],StdDev=x_test[,166]))
test<-rbind(test,data.frame(Activity=y_test[,2],Feature=rep("tBodyAccMag",2947),Mean=x_test[,201],StdDev=x_test[,202]))
test<-rbind(test,data.frame(Activity=y_test[,2],Feature=rep("tGravityAccMag",2947),Mean=x_test[,214],StdDev=x_test[,215]))
test<-rbind(test,data.frame(Activity=y_test[,2],Feature=rep("tBodyAccJerkMag",2947),Mean=x_test[,227],StdDev=x_test[,228]))
test<-rbind(test,data.frame(Activity=y_test[,2],Feature=rep("tBodyGyroMag",2947),Mean=x_test[,240],StdDev=x_test[,241]))
test<-rbind(test,data.frame(Activity=y_test[,2],Feature=rep("tBodyGyroJerkMag",2947),Mean=x_test[,253],StdDev=x_test[,254]))
test<-rbind(test,data.frame(Activity=y_test[,2],Feature=rep("fBodyAcc X",2947),Mean=x_test[,266],StdDev=x_test[,269]))
test<-rbind(test,data.frame(Activity=y_test[,2],Feature=rep("fBodyAcc Y",2947),Mean=x_test[,267],StdDev=x_test[,270]))
test<-rbind(test,data.frame(Activity=y_test[,2],Feature=rep("fBodyAcc Z",2947),Mean=x_test[,268],StdDev=x_test[,271]))
test<-rbind(test,data.frame(Activity=y_test[,2],Feature=rep("fBodyAccJerk X",2947),Mean=x_test[,345],StdDev=x_test[,348]))
test<-rbind(test,data.frame(Activity=y_test[,2],Feature=rep("fBodyAccJerk Y",2947),Mean=x_test[,346],StdDev=x_test[,349]))
test<-rbind(test,data.frame(Activity=y_test[,2],Feature=rep("fBodyAccJerk Z",2947),Mean=x_test[,347],StdDev=x_test[,350]))
test<-rbind(test,data.frame(Activity=y_test[,2],Feature=rep("fBodyGyro X",2947),Mean=x_test[,424],StdDev=x_test[,427]))
test<-rbind(test,data.frame(Activity=y_test[,2],Feature=rep("fBodyGyro Y",2947),Mean=x_test[,425],StdDev=x_test[,428]))
test<-rbind(test,data.frame(Activity=y_test[,2],Feature=rep("fBodyGyro Z",2947),Mean=x_test[,426],StdDev=x_test[,429]))
test<-rbind(test,data.frame(Activity=y_test[,2],Feature=rep("fBodyAccMag",2947),Mean=x_test[,503],StdDev=x_test[,504]))
test<-rbind(test,data.frame(Activity=y_test[,2],Feature=rep("fBodyAccJerkMag",2947),Mean=x_test[,516],StdDev=x_test[,517]))
test<-rbind(test,data.frame(Activity=y_test[,2],Feature=rep("fBodyGyroMag",2947),Mean=x_test[,529],StdDev=x_test[,530]))
test<-rbind(test,data.frame(Activity=y_test[,2],Feature=rep("fBodyGyroJerkMag",2947),Mean=x_test[,542],StdDev=x_test[,543]))
#Create Tidy Data with Column for Activity, Feature, Mean, Standard Deviation for train
train<-data.frame(Activity=y_train[,2],Feature=rep("tBodyAcc X",7352),Mean=x_train[,1],StdDev=x_train[,4])
train<-rbind(train,data.frame(Activity=y_train[,2],Feature=rep("tBodyAcc Y",7352),Mean=x_train[,2],StdDev=x_train[,5]))
train<-rbind(train,data.frame(Activity=y_train[,2],Feature=rep("tBodyAcc Y",7352),Mean=x_train[,3],StdDev=x_train[,6]))
train<-rbind(train,data.frame(Activity=y_train[,2,Feature=rep("tGravityAcc X",7352),Mean=x_train[,41],StdDev=x_train[,44]))
train<-rbind(train,data.frame(Activity=y_train[,2],Feature=rep("tGravityAcc Y",7352),Mean=x_train[,42],StdDev=x_train[,45]))
train<-rbind(train,data.frame(Activity=y_train[,2],Feature=rep("tGravityAcc Z",7352),Mean=x_train[,43],StdDev=x_train[,46]))
train<-rbind(train,data.frame(Activity=y_train[,2],Feature=rep("tBodyAccJerk X",7352),Mean=x_train[,81],StdDev=x_train[,84]))
train<-rbind(train,data.frame(Activity=y_train[,2],Feature=rep("tBodyAccJerk Y",7352),Mean=x_train[,82],StdDev=x_train[,85]))
train<-rbind(train,data.frame(Activity=y_train[,2],Feature=rep("tBodyAccJerk Z",7352),Mean=x_train[,83],StdDev=x_train[,86]))
train<-rbind(train,data.frame(Activity=y_train[,2],Feature=rep("tBodyGyro X",7352),Mean=x_train[,121],StdDev=x_train[,124]))
train<-rbind(train,data.frame(Activity=y_train[,2],Feature=rep("tBodyGyro Y",7352),Mean=x_train[,122],StdDev=x_train[,125]))
train<-rbind(train,data.frame(Activity=y_train[,2],Feature=rep("tBodyGyro Z",7352),Mean=x_train[,123],StdDev=x_train[,126]))
train<-rbind(train,data.frame(Activity=y_train[,2],Feature=rep("tBodyGyroJerk X",7352),Mean=x_train[,161],StdDev=x_train[,164]))
train<-rbind(train,data.frame(Activity=y_train[,2],Feature=rep("tBodyGyroJerk Y",7352),Mean=x_train[,162],StdDev=x_train[,165]))
train<-rbind(train,data.frame(Activity=y_train[,2],Feature=rep("tBodyGyroJerk Z",7352),Mean=x_train[,163],StdDev=x_train[,166]))
train<-rbind(train,data.frame(Activity=y_train[,2],Feature=rep("tBodyAccMag",7352),Mean=x_train[,201],StdDev=x_train[,202]))
train<-rbind(train,data.frame(Activity=y_train[,2],Feature=rep("tGravityAccMag",7352),Mean=x_train[,214],StdDev=x_train[,215]))
train<-rbind(train,data.frame(Activity=y_train[,2],Feature=rep("tBodyAccJerkMag",7352),Mean=x_train[,227],StdDev=x_train[,228]))
train<-rbind(train,data.frame(Activity=y_train[,2],Feature=rep("tBodyGyroMag",7352),Mean=x_train[,240],StdDev=x_train[,241]))
train<-rbind(train,data.frame(Activity=y_train[,2],Feature=rep("tBodyGyroJerkMag",7352),Mean=x_train[,253],StdDev=x_train[,254]))
train<-rbind(train,data.frame(Activity=y_train[,2],Feature=rep("fBodyAcc X",7352),Mean=x_train[,266],StdDev=x_train[,269]))
train<-rbind(train,data.frame(Activity=y_train[,2],Feature=rep("fBodyAcc Y",7352),Mean=x_train[,267],StdDev=x_train[,270]))
train<-rbind(train,data.frame(Activity=y_train[,2],Feature=rep("fBodyAcc Z",7352),Mean=x_train[,268],StdDev=x_train[,271]))
train<-rbind(train,data.frame(Activity=y_train[,2],Feature=rep("fBodyAccJerk X",7352),Mean=x_train[,345],StdDev=x_train[,348]))
train<-rbind(train,data.frame(Activity=y_train[,2],Feature=rep("fBodyAccJerk Y",7352),Mean=x_train[,346],StdDev=x_train[,349]))
train<-rbind(train,data.frame(Activity=y_train[,2],Feature=rep("fBodyAccJerk Z",7352),Mean=x_train[,347],StdDev=x_train[,350]))
train<-rbind(train,data.frame(Activity=y_train[,2],Feature=rep("fBodyGyro X",7352),Mean=x_train[,424],StdDev=x_train[,427]))
train<-rbind(train,data.frame(Activity=y_train[,2],Feature=rep("fBodyGyro Y",7352),Mean=x_train[,425],StdDev=x_train[,428]))
train<-rbind(train,data.frame(Activity=y_train[,2],Feature=rep("fBodyGyro Z",7352),Mean=x_train[,426],StdDev=x_train[,429]))
train<-rbind(train,data.frame(Activity=y_train[,2],Feature=rep("fBodyAccMag",7352),Mean=x_train[,503],StdDev=x_train[,504]))
train<-rbind(train,data.frame(Activity=y_train[,2],Feature=rep("fBodyAccJerkMag",7352),Mean=x_train[,516],StdDev=x_train[,517]))
train<-rbind(train,data.frame(Activity=y_train[,2],Feature=rep("fBodyGyroMag",7352),Mean=x_train[,529],StdDev=x_train[,530]))
train<-rbind(train,data.frame(Activity=y_train[,2],Feature=rep("fBodyGyroJerkMag",7352),Mean=x_train[,542],StdDev=x_train[,543]))
#Create Combined Data Frame
colnames(test)<-c("Activity","Feature","Mean","StdDev")
colnames(train)<-c("Activity","Feature","Mean","StdDev")
combined<-data.frame(test)
combined<-rbind(combined,train)
#Create Means data
CombinedMeans <- aggregate(combined[,3], by =list(combined[,1], combined[,2]), FUN = mean, na.rm = TRUE)
colnames(CombinedMeans)<-c("Activity","Feature","Average")
write